---
- name: update tooling server
  hosts: tooling
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: update todo server
  hosts: todo
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: update nginx server
  hosts: nginx
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: update db server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
