---
- name: update web servers
  hosts: tooling
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
      tags:
        - webserver

- name: update todo server
  hosts: todo
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
      tags:
        - todo

- name: update nginx server
  hosts: nginx
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
      tags:
        - nginx

- name: update db server
  hosts: db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
      tags:
        - db
