---
- name: update web servers
  hosts: tooling
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure Wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
      async: 600      # prevents memory crashes
      poll: 0
      tags:
        - webserver

- name: update todo server
  hosts: todo
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
        force: yes
        install_recommends: no
      tags:
        - todo

- name: update nginx server
  hosts: nginx
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
        force: yes
        install_recommends: no
      tags:
        - nginx

- name: update db server
  hosts: db
  remote_user: ubuntu        # fixed username for DB
  become: yes
  become_user: root
  tasks:
    - name: ensure Wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
        force: yes
        install_recommends: no
      tags:
        - db

