[uat-webservers]
10.0.1.58 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=~/ansible-config-mgt/keys/steghubkey.pem
10.0.1.227 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=~/ansible-config-mgt/keys/steghubkey.pem

[lb]
10.0.1.127 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/ansible-config-mgt/keys/steghubkey.pem

[db-servers]
10.0.1.48 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/ansible-config-mgt/keys/steghubkey.pem

