pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
    }

    environment {
      ANSIBLE_CONFIG = "${WORKSPACE}/deploy/.ansible.cfg"
    }

    stages {

      stage('Initial Cleanup') {
        steps {
          dir("${WORKSPACE}") {
            deleteDir()
          }
        }
      }

      stage('Checkout SCM') {
        steps {
          git branch: 'main', url: 'https://github.com/dimani001/ansible-configuration.git'
        }
      }

      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/.ansible.cfg'
        }
      }

      stage('Run Ansible playbook') {
        steps {
          ansiblePlaybook become: true,
            credentialsId: '29b822eb-48ee-42a4-8953-7fcf8f42ba2e-private-key',
            disableHostKeyChecking: true,
            installation: 'ansible',
            inventory: "${WORKSPACE}/inventory/${params.inventory}",
            playbook: "${WORKSPACE}/playbooks/site.yml"
        }
      }

      stage('Clean Workspace after build') {
        steps {
          cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
        }
      }

    }
}
