pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'ansible_tags', defaultValue: 'webserver', description: 'Ansible tags to run specific roles or tasks')
    }

    environment {
      ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
      ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {

      stage('Initial Cleanup') {
        steps {
          dir("${WORKSPACE}") {
            deleteDir()
          }
        }
      }

      stage('Checkout SCM') {
        steps {
          git branch: 'main', url: 'https://github.com/dimani001/ansible-configuration.git'
        }
      }

      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
        }
      }

      stage('Run Ansible playbook') {
  steps {
    sshagent(['private-key', 'private-key-redhat']) {
      ansiblePlaybook(
        become: true,
        credentialsId: 'private-key',
        disableHostKeyChecking: true,
        installation: 'ansible',
        inventory: "${WORKSPACE}/inventory/${params.inventory}",
        playbook: "${WORKSPACE}/playbooks/site.yml",
        tags: "${params.ansible_tags}"
      )
    }
  }
}

      stage('Clean Workspace after build') {
        steps {
          cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
        }
      }

    }
}
