---
- name: Include dynamic variables
  hosts: all
  become: yes
  tasks:
    - include_vars: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- import_playbook: ../static-assignments/common.yml
  tags:
    - common

- import_playbook: ../static-assignments/artifactory.yml
  tags:
    - artifactory
